New nbdcopy tool.
This tool is currently very simplistic.  For example it makes no
attempt to be efficient or keep multiple requests in flight, and there
are other shortcomings (see TODO).  It's designed as a placeholder for
future work and to allow us to stream in and out from stdin/stdout,
which is something that cannot currently be done with qemu-img
convert, but is very desirable for KubeVirt.

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -71,6 +71,25 @@ requires ()
     }
 }
 
+# Tests that run under check-root should use this.
+requires_root ()
+{
+    if test $(id -u) -ne 0; then
+        echo "$0: test skipped because not running as root"
+        echo "$0: use ‘sudo make check-root’ to run these tests"
+        exit 77
+    fi
+}
+
+# Opposite of requires - the test must not succeed.
+requires_not ()
+{
+    if ( "$@" ) </dev/null >/dev/null 2>&1 ; then
+        echo "$0: test prerequisite is missing or not working"
+        exit 77
+    fi
+}
+
 # pick_unused_port
 #
 # Picks and returns an "unused" port, setting the global variable
