Fix test requirements
Some tests have extra dependencies that may be missing in minimal
deployments (e.g. hexdump), some require kernel modules or support (nbd, fuse)
and others need qemu, but were written to only work with qemu-kvm binary.

All these were fixed to my best knowledge, but of course they are still not
perfect.

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>
(cherry picked from commit c114ee5ccc1adf124c6f12ba0ad4b3fbbc94ef2c)

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -76,6 +76,27 @@ requires ()
     }
 }
 
+# requires_qemu
+#
+# Check that qemu-kvm or qemu-system-$(uname -m) works.  If not, skip the test.
+# If it does, then export the appropriate binary name in $QEMU_BINARY.
+requires_qemu ()
+{
+    local qemu_bin
+    for qemu_bin in "qemu-kvm" "qemu-system-$(uname -m)" "/usr/libexec/qemu-kvm"; do
+        ( "$qemu_bin" --version ) </dev/null >/dev/null 2>&1 || continue
+
+        export QEMU_BINARY="$qemu_bin"
+        break
+    done
+
+    if test -z "$QEMU_BINARY"; then
+        echo "$0: No usable QEMU binary found"
+        echo "$0: test prerequisite is missing or not working"
+        exit 77
+    fi
+}
+
 # Tests that run under check-root should use this.
 requires_root ()
 {
