tests: Test nbd+vsock:// support
I realised there is no explicit test for this in libnbd (although it
is tested in the nbdkit test suite).  This test draws heavily on the
nbdkit test (nbdkit.git/tests/test-vsock.sh).

diff --git a/tests/functions.sh.in b/tests/functions.sh.in
--- a/tests/functions.sh.in
+++ b/tests/functions.sh.in
@@ -145,6 +145,19 @@ requires_caps ()
     done
 }
 
+# Tests that use the vsock interface will fail if vsock is not
+# supported.  On Linux you have to load the kernel module
+# vsock_loopback.  See also
+# https://bugzilla.redhat.com/show_bug.cgi?id=2069558
+requires_vsock_support ()
+{
+    if ! grep -q ^AF_VSOCK /proc/net/protocols ||
+       ! lsmod | grep -q ^vsock_loopback; then
+        echo "$0: test skipped because AF_VSOCK is not supported."
+        exit 77
+    fi
+}
+
 # Tests that run under check-root should use this.
 requires_root ()
 {
